ScratchMVC3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScratchMVC3.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult News()
        {
            return View();
        }
    }
}

ScratchMVC3/Controllers/MembershipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ScratchMVC3.Controllers
{
    public class MembershipController : Controller
    {
        // GET: Membership
        public ActionResult Registration()
        {
            return View();
        }
    }
}

ScratchMVC3/Views/Home/AboutUs.cshtml
@{
    ViewBag.Title = "AboutUs";
}


        <article>
            <p>We are all about building bodies. We let them hit the floor.</p>
        </article>

ScratchMVC3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}


        <article>
            <p>Here, we are building the body.... of this page</p>
        </article>

@section nutrition 
    {
        <article>
            <p>This article is about nutririon</p>
        </article>
    }

        <article>
            <p>Why you so cray cray about building dem bodies?!?!?!</p>
        </article>

@section gainz{
    <article>
        <p>All About dem gainz!</p>
    </article>
}

ScratchMVC3/Views/Home/News.cshtml
@{
    Layout = "~/Views/Shared/_UglyLayout.cshtml";
}

<h2>News</h2>

<article>
    <p>
        The news and newer newsy things</p>
    <h2>EXPERT Journalism!!</h2>
</article>

ScratchMVC3/Views/Membership/Registration.cshtml
@{
    ViewBag.Title = "Register";
}


        <article>
            <p>You're going to register to build your own body.</p>
        </article>

ScratchMVC3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Body Builder Dot Com</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("About Us", "AboutUs", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("News", "News", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Register", "Registration", "Membership", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        @RenderSection("nutrition", false)
        @RenderSection("gainz", false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Body Builder Dot Com</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

ScratchMVC3/Views/Shared/_UglyLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link type="text/css" rel="stylesheet" href="~/Styles/main.css" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="bodyDiv">
        @RenderBody()
    </div>
</body>
</html>